### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by lovedididi** [xiaolLIN/MSSR#5]
Traceback (most recent call last):
  File "/home/yy/MSSR-main/MSSR-main/run_model.py", line 39, in <module>
    run_result = run_recbole(model=args.model, dataset=args.dataset, config_file_list=config_file_list, config_dict=parameter_dict)
  File "/home/yy/MSSR-main/MSSR-main/recbole/quick_start/quick_start.py", line 65, in run_recbole
    best_valid_score, best_valid_result = trainer.fit(
  File "/home/yy/MSSR-main/MSSR-main/recbole/trainer/trainer.py", line 374, in fit
    train_loss = self._train_epoch(train_data, epoch_idx, show_progress=show_progress)
  File "/home/yy/MSSR-main/MSSR-main/recbole/trainer/trainer.py", line 220, in _train_epoch
    losses = loss_func(interaction)
  File "/home/yy/MSSR-main/MSSR-main/recbole/model/sequential_recommender/mssr.py", line 585, in calculate_loss
    seq_output, seq_output_attr = self.forward(item_seq, item_seq_len)        # seq output:  [B, d]
  File "/home/yy/MSSR-main/MSSR-main/recbole/model/sequential_recommender/mssr.py", line 573, in forward
    trm_output, trm_output_attr = self.trm_encoder(input_emb, self.fea_seq_emb, position_embedding, extended_attention_mask, output_all_encoded_layers=True)
  File "/home/yy/.conda/envs/recbole/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yy/.conda/envs/recbole/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yy/MSSR-main/MSSR-main/recbole/model/sequential_recommender/mssr.py", line 303, in forward
    hidden_states, hidden_states_attr = layer_module(hidden_states, attribute_hidden_states, position_embedding, [hidden_states_attr],
  File "/home/yy/.conda/envs/recbole/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yy/.conda/envs/recbole/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yy/MSSR-main/MSSR-main/recbole/model/sequential_recommender/mssr.py", line 243, in forward
    attention_output, attention_output_attr = self.multi_head_attention(hidden_states, attribute_embed,
  File "/home/yy/.conda/envs/recbole/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yy/.conda/envs/recbole/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yy/MSSR-main/MSSR-main/recbole/model/sequential_recommender/mssr.py", line 193, in forward
    ac_attention, _ = self.fusion_layer(ac_attention * self.fusion_w.unsqueeze(0).unsqueeze(0).unsqueeze(-1))
AttributeError: 'int' object has no attribute 'unsqueeze'

- [ ] ：这里self.fusion_w似乎是int，但是当我修改后依旧报错。请问如何修改。

**Comment by xiaolLIN** [comment]
这里的self.fusion_w 应该是与 mssr.py line 269 的crs_w_i 具有相同shape的张量。

**Comment by xiaolLIN** [comment]
@lovedididi  我运行这个project，运行正常，没有您展示出来的报错信息。请您下载重新试试

**Comment by lovedididi** [comment]
@xiaolLIN 我重新下载，运行还是这个问题。我发现在运行过程中fusion_w 和fusion_wc 的值是int 1。应该这这个代码的作用，在mssr.py模块下172-175：
        self.fusion_w = fusion_w
        self.fusion_wc = fusion_wc
        if self.ada_fuse != 1:
            self.fusion_w, self.fusion_wc = 1, 1
请问我应该如何修改这个代码。

**Comment by xiaolLIN** [comment]
原来的代码中当ada_fuse != 1时存在bug，已修复，请重新查看mssr.py。

**Comment by lovedididi** [comment]
@xiaolLIN 你好，上个问题已经解决了，但是在运行过程中出现了另一个问题。

Traceback (most recent call last):
  File "/home/yy/MSSR-main/MSSR-main/run_model.py", line 39, in <module>
    run_result = run_recbole(model=args.model, dataset=args.dataset, config_file_list=config_file_list, config_dict=parameter_dict)
  File "/home/yy/MSSR-main/MSSR-main/recbole/quick_start/quick_start.py", line 65, in run_recbole
    best_valid_score, best_valid_result = trainer.fit(
  File "/home/yy/MSSR-main/MSSR-main/recbole/trainer/trainer.py", line 374, in fit
    train_loss = self._train_epoch(train_data, epoch_idx, show_progress=show_progress)
  File "/home/yy/MSSR-main/MSSR-main/recbole/trainer/trainer.py", line 220, in _train_epoch
    losses = loss_func(interaction)
  File "/home/yy/MSSR-main/MSSR-main/recbole/model/sequential_recommender/mssr.py", line 656, in calculate_loss
    total_loss = loss
UnboundLocalError: local variable 'loss' referenced before assignment

我查看一下代码发现在mssr.py模块下601-605代码：
if self.config['ip_mode'] == 'gating':
 # seq output [B,d]
      gating = self.item_pred_gating(seq_output, seq_output_attr)  # [B, I]
       logits = gating * logits_ii + (1 - gating) * logits_cc
loss = self.loss_fct(logits, pos_items)
这里的logits似乎没有赋值， 我将loss = self.loss_fct(logits, pos_items)缩进到if中仍出现：
UnboundLocalError: local variable 'logits' referenced before assignment

**Comment by xiaolLIN** [comment]
@lovedididi  mssr.py 在 line 604 已增加判断分支，控制在非gating的方式下，logits直接相加。 两路判断下，已确保logits被赋值。

**Comment by lovedididi** [comment]
@xiaolLIN 感谢您的帮助。我已经用亚马逊18年数据在上面跑了。但是还有一个疑问，就是parser.add_argument('--result_file', type=str)，result_file在运行后是一个None，报错如下：

Traceback (most recent call last):
  File "/home/yy/MSSR-main/MSSR-main/run_model.py", line 44, in <module>
    with open(args.result_file, 'a+') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType

这里我是不是应该在参数上添加一个默认路径。

**Comment by lovedididi** [comment]
@xiaolLIN 当我用亚马逊的sports18年的数据运行代码时，出现了:

Trainable parameters: 2327956
Fri 29 Nov 2024 16:08:23 INFO  epoch 0 training [time: 53.61s, train loss: 32990.8503]
Fri 29 Nov 2024 16:08:23 INFO   
Fri 29 Nov 2024 16:09:15 INFO  epoch 1 training [time: 52.50s, train loss: 14318.1646]
Fri 29 Nov 2024 16:09:21 INFO  epoch 1 evaluating [time: 5.45s, valid_score: 0.071000]
Fri 29 Nov 2024 16:09:21 INFO  valid result: 
ndcg@5 : 0.0668    ndcg@10 : 0.071    hit@5 : 0.0911    hit@10 : 0.104    
Fri 29 Nov 2024 16:09:21 INFO  Saving current best: ./saved/Amazon_Sports_and_Outdoors/MSSR-Nov-29-2024_16-07-29.pth
Fri 29 Nov 2024 16:09:21 INFO   
Fri 29 Nov 2024 16:09:21 INFO  Loading model structure and parameters from ./saved/Amazon_Sports_and_Outdoors/MSSR-Nov-29-2024_16-07-29.pth
Fri 29 Nov 2024 16:09:26 INFO  best valid : {'ndcg@5': 0.0668, 'ndcg@10': 0.071, 'hit@5': 0.0911, 'hit@10': 0.104}
Fri 29 Nov 2024 16:09:26 INFO  test result: {'ndcg@5': 0.0665, 'ndcg@10': 0.0707, 'hit@5': 0.0859, 'hit@10': 0.0989}

仅仅运行两次就结束了，似乎有点不太正常。亚马逊toys18数据也是如此。

**Comment by xiaolLIN** [comment]
@lovedididi  嗯，是的。
